# encoding: utf-8
class CreateShippingCompanies < ActiveRecord::Migration
  def change
    create_table :shipping_companies do |t|
      t.string :name

      t.timestamps
    end
    #Populate default data
    ShippingCompany.create :name => "AIDA Cruises"
    ShippingCompany.create :name => "Deilmann Kreuzfahrten"
    ShippingCompany.create :name => "Nicko Tours"
    ShippingCompany.create :name => "Costa Kreuzfahrten"
    ShippingCompany.create :name => "Croisi Europe"
    ShippingCompany.create :name => "Hurtigruten"
    ShippingCompany.create :name => "Phoenix"
    ShippingCompany.create :name => "Norwegian Cruise Line"
    ShippingCompany.create :name => "TransOcean"
    ShippingCompany.create :name => "Carnival Cruise Lines"
    ShippingCompany.create :name => "Viking"
    ShippingCompany.create :name => "MSC Kreuzfahrten"
    ShippingCompany.create :name => "Hapag-Lloyd Kreuzfahrten"
    ShippingCompany.create :name => "Hansa Kreuzfahrten"
    ShippingCompany.create :name => "Cunard"
    ShippingCompany.create :name => "Holland America"
    ShippingCompany.create :name => "Royal Caribbean Cruise Line"
    ShippingCompany.create :name => "Windstar Cruises"
    ShippingCompany.create :name => "Delphin Kreuzfahrten"
    ShippingCompany.create :name => "Walt Disney's Cruise Line"
    ShippingCompany.create :name => "Seabourn"
    ShippingCompany.create :name => "Celebrity Cruises"
    ShippingCompany.create :name => "Sea Cloud Cruises"
    ShippingCompany.create :name => "Regent Seven Seas Cruises"
    ShippingCompany.create :name => "Silversea Cruises"
    ShippingCompany.create :name => "Crystal Cruises"
    ShippingCompany.create :name => "Nautilus Seereisen"
    ShippingCompany.create :name => "Plantours & Partner"
    ShippingCompany.create :name => "Princess Cruises"
    ShippingCompany.create :name => "Cruceros Australis"
    ShippingCompany.create :name => "Quark Expeditions"
    ShippingCompany.create :name => "Louis Cruise Lines"
    ShippingCompany.create :name => "A-ROSA"
    ShippingCompany.create :name => "China Regal Cruises"
    ShippingCompany.create :name => "SeaDream Yacht Club"
    ShippingCompany.create :name => "Color Line"
    ShippingCompany.create :name => "Lüftner Cruises"
    ShippingCompany.create :name => "Compagnie du Ponant"
    ShippingCompany.create :name => "Clipper Cruises"
    ShippingCompany.create :name => "Club Med Cruises"
    ShippingCompany.create :name => "Oceania Cruises"
    ShippingCompany.create :name => "Gebeco"
    ShippingCompany.create :name => "TUI"
    ShippingCompany.create :name => "Windjammer Barefoot Cruises"
    ShippingCompany.create :name => "Château la Chassagne"
    ShippingCompany.create :name => "Neckermann"
    ShippingCompany.create :name => "Olympia Reisen"
    ShippingCompany.create :name => "Oceanstar"
    ShippingCompany.create :name => "Aranui Cruises"
    ShippingCompany.create :name => "VSOE Orient-Express"
    ShippingCompany.create :name => "Inmaris"
    ShippingCompany.create :name => "Nomade Yachting Bora Bora"
    ShippingCompany.create :name => "Riva Tours"
    ShippingCompany.create :name => "Sirene Cruises"
    ShippingCompany.create :name => "Bahriyeli Yachtcharter"
    ShippingCompany.create :name => "ResidenSea"
    ShippingCompany.create :name => "North Star Cruises"
    ShippingCompany.create :name => "Monarch Classic Cruises"
    ShippingCompany.create :name => "DERTOUR Flusskreuzfahrten"
    ShippingCompany.create :name => "Skorpios"
    ShippingCompany.create :name => "Club Magic Life"
    ShippingCompany.create :name => "Poseidon Arctic Voyages"
    ShippingCompany.create :name => "Sailing-Classics"
    ShippingCompany.create :name => "DCS Touristik"
    ShippingCompany.create :name => "Azamara Club Cruises"
    ShippingCompany.create :name => "Stella Maris Yachting"
    ShippingCompany.create :name => "Nees Reisen"
    ShippingCompany.create :name => "OFT Reisen"
    ShippingCompany.create :name => "1A Vista Reisen"
    ShippingCompany.create :name => "Gvidon Tours"
    ShippingCompany.create :name => "Majestic America Line"
    ShippingCompany.create :name => "ETI"
    ShippingCompany.create :name => "Transorient"
    ShippingCompany.create :name => "Star Clippers"
    ShippingCompany.create :name => "The Adventure Fleet"
    ShippingCompany.create :name => "Ikarus Tours"
    ShippingCompany.create :name => "Schlienz-Reisen"
    ShippingCompany.create :name => "Elegant Cruises & Tours"
    ShippingCompany.create :name => "Premicon Line"
    ShippingCompany.create :name => "TUI Cruises"
    ShippingCompany.create :name => "Royal Holidays"
    ShippingCompany.create :name => "The Majestic Line"
    ShippingCompany.create :name => "Pandaw River Cruises"
    ShippingCompany.create :name => "Lernidee"
    ShippingCompany.create :name => "Hansa Touristik"
    ShippingCompany.create :name => "Bavaria Fernreisen"
    ShippingCompany.create :name => "Variety Cruises"
    ShippingCompany.create :name => "Oberoi Hotels & Resorts"
    ShippingCompany.create :name => "Helios Reisen"
    ShippingCompany.create :name => "DERTOUR Kreuzfahrten"
    ShippingCompany.create :name => "Colibri UmweltReisen"
    ShippingCompany.create :name => "Iberostar"
    ShippingCompany.create :name => "Coral Princess Cruises"
    ShippingCompany.create :name => "Advenation"
    ShippingCompany.create :name => "ES SELECT"
    ShippingCompany.create :name => "Polar Kreuzfahrten"
    ShippingCompany.create :name => "Cruising Reisen"
    ShippingCompany.create :name => "Meier´s Weltreisen"
    ShippingCompany.create :name => "Paul Gauguin Cruises"
    ShippingCompany.create :name => "Costa Kreuzfahrten"
    ShippingCompany.create :name => "MSC Kreuzfahrten"
    ShippingCompany.create :name => "nordic holidays"
    ShippingCompany.create :name => "Vista Travel"
    ShippingCompany.create :name => "Pullmantur Cruises"
  end
end
